### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by JBlond** [bircher/php-merge#6]
Please add PHP 8 support to this lib.

**Comment by bircher** [comment]
Hi, I think just requiring bircher/php-merge should work on php8. I just released 4.0.0 which switched the git-wrapper library to the supported one that also works on php 8. Which means I can run tests on php 8.1.
I have yet to figure out how to get CI working again since travis is not working. But I test stuff locally with php 7.3 and --prefer-lowest and 8.1. and both pass phpunit...

**Comment by JBlond** [comment]
Thanks! It works now!
